# This is a basic workflow to help you get started with Actions

name: Deploy FTP

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: Upload ftp
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ env.FTP_HOST }}
        username: ${{ env.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ env.FTP_REMOTEFOLDER }}
